### ISSUE TITLE
error: no matching function for call to ‘v8::Value::ToObject()’

### ISSUE THREAD

**Issue by JsBergbau** [easybotics/node-red-contrib-easybotics-air-quality#8]
I'm trying to install but I get this error among a lot others
```
../src/serialport.cpp:48:53: error: no matching function for call to ‘v8::Value::ToObject()’
   v8::Local<v8::Object> options = info[1]->ToObject();
```
Node-RED Version 1.2.5
Node.js Version 12.19.0

**Comment by ryanmich251** [comment]
This should hopefully be fixed in the latest version (0.6.9), the 'serialport' dependency was set to an old version that didn't support node.js 12 and gave a bunch of errors like that. Feel free to reopen this issue if this is still a problem with version 0.6.9.
